kelontong/urls.py
from django.urls import path
from . import views 
urlpatterns = [
    path('', views.KelontongIndex, name="KelontongIndex"),
    path('pembelian/', views.KelontongPembelian, name="KelontongPembelian"),
    path('penjualan/', views.KelontongPenjualan, name="KelontongPenjualan"),
    path('penjualan/<str:namabarang>', views.CekBarang, name="CekBarang"),

]

pos/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('kelontong/', include(('kelontong.urls', 'kelontong'), namespace='kelontong')),
]

kelontong/models.py
from django.db import models
class barang(models.Model):
    nama_barang = models.CharField(max_length=10)
    harga_beli = models.IntegerField()
    harga_jual = models.IntegerField()
    banyak_barang = models.IntegerField()
    jenisbarang = (
        ('OBAT-OBATAN','obat-obatan'),
        ('MAKANAN DAN MINUMAN RINGAN ','makananminuman'),
    )
    jenis_barang = models.CharField(choices=jenisbarang, max_length=30, default='lain-lain')
    status = (
        ('ADA', 'ADA'),
        ('KOSONG', 'KOSONG'),
    )
    tgl_beli = models.DateField(auto_now_add=True, null=True, blank=True)
    tgl_kdlws = models.DateField()
    status = models.CharField(choices=status, max_length=10)
    def __str__(self):

        return "{} {}".format(self.id, self.nama_barang)
class barangJualan(models.Model):
    tanggal_jual = models.DateField(auto_now_add=True,blank=True)
    nama_barang = models.CharField(max_length=10)
    banyak_beli = models.IntegerField()
    def __str__(self):
    
        return "{} {}".format(self.id, self.nama_barang)

wifi/models.py
from django.db import models

# Create your models here.

kelontong/views.py
from django.shortcuts import render, redirect
from .table import FormPembelian, FormJualan
from django.db.models import Max, Min, F
from .models import barang, barangJualan
def KelontongIndex(request):
    barangs = barang.objects.all()
    
    context={
        'title':'TOKO KELONTONG',
        'head':'SELAMAT DATANG',
        'table': barangs,
    }
    return render(request, 'kelontong/index.html', context)
def KelontongPembelian(request):
    tableForm = FormPembelian(request.POST or None)
    if request.method == "POST":
        if tableForm.is_valid():
            tableForm.save()
            return redirect('kelontong:KelontongIndex')
        
    context={
        'title':'PEMBELIAN',
        'table': tableForm,
    }
    return render(request, 'kelontong/pembelian.html', context)
def KelontongPenjualan(request):
    Formjualan = FormJualan(request.POST or None)
    if request.method == "POST":
          if Formjualan.is_valid():
              nama_barang = Formjualan.cleaned_data['nama_barang']
              print(nama_barang)
              Formjualan.save()
              return redirect('kelontong:KelontongPenjualan')        
    context={
        'title':'PENJUALAN',
        'table': Formjualan,
    }
    return render(request, 'kelontong/penjualan.html', context)

def CekBarang(request, namabarang):
    if barang.objects.filter(nama_barang__iexact = namabarang ).exists():
        a = "on"
        print(a)
        print('data ada')
        return redirect('kelontong:KelontongPenjualan')
    else:
        a = "off"
        print(a)
        print('data kosong')
        return redirect('kelontong:KelontongPenjualan')
    return render(request, 'kelontong/penjualan.html', context)

pos/views.py
from django.shortcuts import render
def index(request):
    context={
        'title':'POS',
        'head':'POINT_OF_SALES',
    }
    return render(request, 'index.html', context)
# Create your views here.

wifi/views.py
from django.shortcuts import render

# Create your views here.

kelontong/templates/kelontong/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include "snippets/styles.html" %}
    {% block gaya %}
    
    {% endblock gaya%}
    <title>{{title}}</title>
</head>
<body>
{% include "snippets/navKelontong.html" %}

{% block satu %}
<div class="main" style="margin-left: 20px;">
    <h4>TABEL BARANG</h4>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">NAMA_BARANG</th>
          <th scope="col">HARGA_BELI</th>
          <th scope="col">HARGA_JUAL</th>
          <th scope="col">BANYAK_BARANG</th>
          <th scope="col">JENIS_BARANG</th>
          <th scope="col">STATUS</th>
        </tr>
      </thead>
      <tbody>
        {% for a in table %}
        <tr>
          <td>{{a.id}}</td>
          <td>{{a.nama_barang}}</td>
          <td>{{a.harga_beli}}</td>
          <td>{{a.harga_jual}}</td>
          <td>{{a.banyak_barang}}</td>
          <td>{{a.jenis_barang}}</td>
          <td>{{a.status}}</td>
        </tr>
        {% endfor %}
      </tbody>
      <div class="main" style="margin-left: 20px; margin-bottom: 10px;">
        <a href="{% url "kelontong:KelontongPembelian"%}" class="btn btn-primary btn-md active" role="button" aria-pressed="true">Tambahakan</a>
        </div>
    </table>
{% endblock satu %}

{% include "snippets/script.html" %}
</body>
</html>

kelontong/templates/kelontong/pembelian.html
{% extends "kelontong/index.html" %}
{% block satu %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <table>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>{{table.nama_barang.label}}</label>
                    {{table.nama_barang}}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>{{table.harga_beli.label}}</label>
                    {{table.harga_beli}}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>{{table.harga_jual.label}}</label>
                    {{table.harga_jual}}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>{{table.banyak_barang.label}}</label>
                    {{table.banyak_barang}}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>{{table.tgl_kdlws.label}}</label>
                    {{table.tgl_kdlws}}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>{{table.jenis_barang.label}}</label>
                    {{table.jenis_barang}}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>{{table.status.label}}</label>
                    {{table.status}}
                </div>
            </div>
        </table>
        <button type="submit" class="btn btn-primary">Tambahkan</button>
    </form>
</div>
{% endblock satu %}

kelontong/templates/kelontong/penjualan.html
{% extends "kelontong/index.html" %}
{% block satu %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <table>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>{{table.nama_barang.label}}</label>
                    {{table.nama_barang}}
                    <a href="{% url "kelontong:CekBarang" "tembelek" %}" class="btn btn-warning btn-sm active" role="button" aria-pressed="true" style="margin-top: 10px;">Cek</a></td>
                </div>
            </div>            
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>{{table.banyak_beli.label}}</label>
                    {{table.banyak_beli}}
                </div>
            </div>
        </table>
    {% if a == "on" %}
    <button type="submit" class="btn btn-primary" >Tambahkan</button>
    {% else %}
    <button type="submit" class="btn btn-primary" disable>Tambahkan</button>
    {% endif %}
    </form>
</div>
{% endblock satu %}

templates/dasar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include "snippets/styles.html" %}
    {% block gaya %}
    
    {% endblock gaya%}
    <title>{{title}}</title>
</head>
<body>
{% include "snippets/nav.html" %}

{% block satu %}
{% endblock satu %}

{% include "snippets/script.html" %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include "snippets/styles.html" %}
    {% block gaya %}
    
    {% endblock gaya%}
    <title>{{title}}</title>
</head>
<body>
{% include "snippets/nav.html" %}

{% block satu %}
{% endblock satu %}

{% include "snippets/script.html" %}
</body>
</html>

templates/snippets/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">POINT OF SALES</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="">Home</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "kelontong:KelontongIndex" %}">Toko kelontong</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">Wifi</a>
      </li>
    </ul>
  </div>
</nav>

templates/snippets/navKelontong.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url "kelontong:KelontongIndex" %}">TOKO KELONTONG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url "kelontong:KelontongIndex" %}">Home</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "kelontong:KelontongPembelian" %}">Pembelian</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "kelontong:KelontongPenjualan" %}">Penjualan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="">Hutang</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="">Cash</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/">Kembali</a>
        </li>
      </ul>
    </div>
  </nav>

templates/snippets/script.html
{% load static %}
<script src="{% static "vendor\jquery\jquery.js" %}" type="text/javascript" charset="utf-8" async defer></script>
<script src="{% static "vendor\popper\popper.js" %}" type="text/javascript" charset="utf-8" async defer></script>
<script src="{% static "vendor\bootstrap\bootstrap.js" %}" type="text/javascript" charset="utf-8" async defer></script>
<script src="{% static "js\scrolling.js" %}" type="text/javascript" charset="utf-8" async defer></script>

templates/snippets/styles.html
{% load static%}
<link rel="stylesheet" href="{% static "vendor\bootstrap\bootstrap.css" %}">